set expandtab
set nocompatible 
filetype off   
filetype plugin indent on " Put your non-Plugin stuff after this line
syntax enable 
set nu 
set smartindent 
set tabstop=4
set shiftwidth=4 
set expandtab
