set expandtab
set nocompatible 
filetype off 
set rtp+=~/.vim/bundle/Vundle.vim 
call vundle#begin() 
Plugin 'gmarik/Vundle.vim' "required
Plugin 'tpope/vim-fugitive' "required 
call vundle#end()            
filetype plugin indent on " Put your non-Plugin stuff after this line
syntax enable 
set nu 
set smartindent 
set tabstop=4
set shiftwidth=4 
set expandtab
